var searchData=
[
  ['emptybufexception_54',['EmptyBufException',['../classEmptyBufException.html',1,'']]],
  ['enc_5f2_5fmm_55',['ENC_2_MM',['../group__movement__id.html#ga7be555832d399f6fc86d82551f6fef54',1,'roomba_movement.hpp']]],
  ['encoder_5fdrive_5fstraight_56',['encoder_drive_straight',['../group__movement__id.html#gadb48e557019e32d0195dd88c09461883',1,'encoder_drive_straight(int speed, std::function&lt; bool()&gt; condition, bool stop, double correction_proportion, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga8faaceac5a8eaa51ccff1a942f5dd6cb',1,'encoder_drive_straight(int max_speed, double cm, bool stop, int min_speed, double correction_proportion, double accel_per_sec, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__movement__id.html#gadb48e557019e32d0195dd88c09461883',1,'encoder_drive_straight(int speed, std::function&lt; bool()&gt; condition, bool stop=get_config().getBool(&quot;roomba_stop&quot;), double correction_proportion=get_config().getDouble(&quot;roomba_correction_proportion&quot;), int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga8faaceac5a8eaa51ccff1a942f5dd6cb',1,'encoder_drive_straight(int speed, double cm, bool stop=get_config().getBool(&quot;roomba_stop&quot;), int min_speed=get_config().getInt(&quot;roomba_min_speed&quot;), double correction_proportion=get_config().getDouble(&quot;roomba_correction_proportion&quot;), double accel_per_sec=get_config().getDouble(&quot;roomba_accel_per_sec&quot;), int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp']]],
  ['encoder_5fdrive_5fstraight_5fcm_57',['encoder_drive_straight_cm',['../group__python__functions__id.html#ga3b734eec6852057472c892b3c303cf2a',1,'ihs_bindings']]],
  ['encoder_5fdrive_5fstraight_5ffn_58',['encoder_drive_straight_fn',['../group__python__functions__id.html#ga82e31f9c75bf819512702111ec3a2daa',1,'ihs_bindings']]],
  ['encoder_5fdrive_5fstraight_5fpid_59',['encoder_drive_straight_pid',['../group__movement__id.html#ga0da878ea2665cd58355b78b446ac5628',1,'encoder_drive_straight_pid(int speed, double cm, double proportional_coefficient, double integral_coefficient, double derivative_coefficient, bool stop=get_config().getBool(&quot;roomba_stop&quot;), int min_speed=get_config().getInt(&quot;roomba_min_speed&quot;), double accel_per_sec=get_config().getDouble(&quot;roomba_accel_per_sec&quot;), int updates_per_second=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga0da878ea2665cd58355b78b446ac5628',1,'encoder_drive_straight_pid(int speed, double cm, double proportional_coefficient, double integral_coefficient, double derivative_coefficient, bool stop, int min_speed, double accel_per_sec, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__python__functions__id.html#ga64fb1ef69c99e85964ff61ca3b50451e',1,'ihs_bindings.encoder_drive_straight_pid()']]],
  ['encoder_5fturn_5fdegrees_60',['encoder_turn_degrees',['../group__movement__id.html#ga5477b70d1d2eea55385f70e2385f0dea',1,'encoder_turn_degrees(int max_speed, double degrees, int min_speed, double accel_per_sec, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga12b7dffa4257becbf2ef18a7c8323d02',1,'encoder_turn_degrees(Speed turn_speed, double degrees, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__python__functions__id.html#ga8ede7a3952b52fd688b01ff3f8846f8e',1,'ihs_bindings.encoder_turn_degrees()'],['../group__movement__id.html#ga5477b70d1d2eea55385f70e2385f0dea',1,'encoder_turn_degrees(int max_speed, double degrees, int min_speed=get_config().getInt(&quot;roomba_min_speed&quot;), double accel_per_sec=get_config().getDouble(&quot;roomba_accel_per_sec&quot;), int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga12b7dffa4257becbf2ef18a7c8323d02',1,'encoder_turn_degrees(Speed turn_speed, double degrees, int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp']]],
  ['encoder_5fturn_5fdegrees_5fv2_61',['encoder_turn_degrees_v2',['../group__python__functions__id.html#gac366f7f12638dc7ac6a0dfa0f32991f9',1,'ihs_bindings']]],
  ['encodersingleton_62',['EncoderSingleton',['../classEncoderSingleton.html',1,'']]],
  ['encodersubscriber_63',['EncoderSubscriber',['../classEncoderSubscriber.html#a2e52bceaa4ef9f2019971bb068abfa08',1,'EncoderSubscriber::EncoderSubscriber()'],['../classEncoderSubscriber.html',1,'EncoderSubscriber'],['../classihs__bindings_1_1EncoderSubscriber.html',1,'ihs_bindings.EncoderSubscriber']]]
];
