var searchData=
[
  ['accelerate_5fforward_5flinear_208',['accelerate_forward_linear',['../group__movement__id.html#ga80b54a179f240432f515e62199b5fb57',1,'accelerate_forward_linear(int from_speed, int to_speed, double accel_per_sec=get_config().getDouble(&quot;linear_accel&quot;), int updates_per_sec=get_config().getInt(&quot;accelerate_updates_per_sec&quot;)):&#160;accelerate.cpp'],['../group__movement__id.html#ga80b54a179f240432f515e62199b5fb57',1,'accelerate_forward_linear(int from_speed, int to_speed, double accel_per_sec, int updates_per_sec):&#160;accelerate.cpp']]],
  ['accelerate_5fforward_5fsin_209',['accelerate_forward_sin',['../group__movement__id.html#ga4ffb81e42fb8b907261911ee37c887ca',1,'accelerate_forward_sin(int from_speed, int to_speed, double avg_accel_per_sec=get_config().getDouble(&quot;sinusoidal_accel&quot;), int updates_per_sec=get_config().getInt(&quot;accelerate_updates_per_sec&quot;)):&#160;accelerate.cpp'],['../group__movement__id.html#ga4ffb81e42fb8b907261911ee37c887ca',1,'accelerate_forward_sin(int from_speed, int to_speed, double avg_accel_per_sec, int updates_per_sec):&#160;accelerate.cpp']]],
  ['accelerate_5flinear_210',['accelerate_linear',['../group__movement__id.html#gab62164c7d92d822e4c25b27c1cf9400f',1,'accelerate_linear(Speed from_speed, Speed to_speed, double accel_per_sec=get_config().getDouble(&quot;linear_accel&quot;), int updates_per_sec=get_config().getInt(&quot;accelerate_updates_per_sec&quot;)):&#160;accelerate.cpp'],['../group__movement__id.html#gab62164c7d92d822e4c25b27c1cf9400f',1,'accelerate_linear(Speed from_speed, Speed to_speed, double accel_per_sec, int updates_per_sec):&#160;accelerate.cpp']]],
  ['accelerate_5fsinusoidal_211',['accelerate_sinusoidal',['../group__movement__id.html#gabe9ca16ac8e8fcf9f003d6bd19f6b84a',1,'accelerate_sinusoidal(Speed from_speed, Speed to_speed, double accel_per_sec=get_config().getDouble(&quot;sinusoidal_accel&quot;), int updates_per_sec=get_config().getInt(&quot;accelerate_updates_per_sec&quot;)):&#160;accelerate.cpp'],['../group__movement__id.html#gabe9ca16ac8e8fcf9f003d6bd19f6b84a',1,'accelerate_sinusoidal(Speed from_speed, Speed to_speed, double accel_per_sec, int updates_per_sec):&#160;accelerate.cpp']]],
  ['acceleratecontroller_212',['AccelerateController',['../classAccelerateController.html#a8f68218b4c73fb65fdc18e51202801a2',1,'AccelerateController']]],
  ['accumulator_213',['Accumulator',['../classAccumulator.html#a7e09fb5f2cf1adf54d86a8c3cacaed53',1,'Accumulator']]],
  ['align_5fwith_5fblack_214',['align_with_black',['../group__movement__id.html#ga45c6360af2fcee806597329ffa3400a6',1,'align_with_black(int speed, int correction_speed, Cliff cliff_sensor_l, Cliff cliff_sensor_r, bool stop=get_config().getBool(&quot;align_stop&quot;), int updates_per_second=get_config().getInt(&quot;align_updates_per_sec&quot;)):&#160;line_follow.cpp'],['../group__movement__id.html#ga45c6360af2fcee806597329ffa3400a6',1,'align_with_black(int speed, int correction_speed, Cliff cliff_sensor_l, Cliff cliff_sensor_r, bool stop, int updates_per_second):&#160;line_follow.cpp']]],
  ['align_5fwith_5fwhite_215',['align_with_white',['../group__movement__id.html#gafe29ef60cc3f3ab9dd44cb96ea19a93a',1,'align_with_white(int speed, int correction_speed, Cliff cliff_sensor_l, Cliff cliff_sensor_r, bool stop=get_config().getBool(&quot;align_stop&quot;), int updates_per_second=get_config().getInt(&quot;align_updates_per_sec&quot;)):&#160;line_follow.cpp'],['../group__movement__id.html#gafe29ef60cc3f3ab9dd44cb96ea19a93a',1,'align_with_white(int speed, int correction_speed, Cliff cliff_sensor_l, Cliff cliff_sensor_r, bool stop, int updates_per_second):&#160;line_follow.cpp']]]
];
