var searchData=
[
  ['encoder_5fdrive_5fstraight_262',['encoder_drive_straight',['../group__movement__id.html#ga91c8625fdafbcec44668480c4002f213',1,'encoder_drive_straight(int speed, double cm, bool stop=get_config().getBool(&quot;roomba_stop&quot;), int min_speed=get_config().getInt(&quot;roomba_min_speed&quot;), double correction_proportion=get_config().getDouble(&quot;roomba_correction_proportion&quot;), double accel_per_sec=get_config().getDouble(&quot;roomba_accel_per_sec&quot;), int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#gac91d60fb05bc2d6a0f8f11d1f4d944ee',1,'encoder_drive_straight(int speed, std::function&lt; bool()&gt; condition, bool stop=get_config().getBool(&quot;roomba_stop&quot;), double correction_proportion=get_config().getDouble(&quot;roomba_correction_proportion&quot;), int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#gac91d60fb05bc2d6a0f8f11d1f4d944ee',1,'encoder_drive_straight(int speed, std::function&lt; bool()&gt; condition, bool stop, double correction_proportion, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga91c8625fdafbcec44668480c4002f213',1,'encoder_drive_straight(int max_speed, double cm, bool stop, int min_speed, double correction_proportion, double accel_per_sec, int updates_per_sec):&#160;roomba_movement.cpp']]],
  ['encoder_5fdrive_5fstraight_5fcm_263',['encoder_drive_straight_cm',['../group__python__functions__id.html#ga271109a67ab0795f2cddecab946f3dd3',1,'ihs_bindings']]],
  ['encoder_5fdrive_5fstraight_5ffn_264',['encoder_drive_straight_fn',['../group__python__functions__id.html#gaa1323a6bb7da446ad625f7cb1ea662de',1,'ihs_bindings']]],
  ['encoder_5fdrive_5fstraight_5fpid_265',['encoder_drive_straight_pid',['../group__movement__id.html#ga0da878ea2665cd58355b78b446ac5628',1,'encoder_drive_straight_pid(int speed, double cm, double proportional_coefficient, double integral_coefficient, double derivative_coefficient, bool stop=get_config().getBool(&quot;roomba_stop&quot;), int min_speed=get_config().getInt(&quot;roomba_min_speed&quot;), double accel_per_sec=get_config().getDouble(&quot;roomba_accel_per_sec&quot;), int updates_per_second=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga0da878ea2665cd58355b78b446ac5628',1,'encoder_drive_straight_pid(int speed, double cm, double proportional_coefficient, double integral_coefficient, double derivative_coefficient, bool stop, int min_speed, double accel_per_sec, int updates_per_second):&#160;roomba_movement.cpp'],['../group__python__functions__id.html#ga64fb1ef69c99e85964ff61ca3b50451e',1,'ihs_bindings.encoder_drive_straight_pid()']]],
  ['encoder_5fturn_5fdegrees_266',['encoder_turn_degrees',['../group__movement__id.html#ga5477b70d1d2eea55385f70e2385f0dea',1,'encoder_turn_degrees(int max_speed, double degrees, int min_speed=get_config().getInt(&quot;roomba_min_speed&quot;), double accel_per_sec=get_config().getDouble(&quot;roomba_accel_per_sec&quot;), int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga12b7dffa4257becbf2ef18a7c8323d02',1,'encoder_turn_degrees(Speed turn_speed, double degrees, int updates_per_sec=get_config().getInt(&quot;roomba_updates_per_sec&quot;)):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga5477b70d1d2eea55385f70e2385f0dea',1,'encoder_turn_degrees(int max_speed, double degrees, int min_speed, double accel_per_sec, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__movement__id.html#ga12b7dffa4257becbf2ef18a7c8323d02',1,'encoder_turn_degrees(Speed turn_speed, double degrees, int updates_per_sec):&#160;roomba_movement.cpp'],['../group__python__functions__id.html#ga8ede7a3952b52fd688b01ff3f8846f8e',1,'ihs_bindings.encoder_turn_degrees(Speed turn_speed, float degrees, int updates_per_sec=...)']]],
  ['encoder_5fturn_5fdegrees_5fv2_267',['encoder_turn_degrees_v2',['../group__python__functions__id.html#gac366f7f12638dc7ac6a0dfa0f32991f9',1,'ihs_bindings']]]
];
